### PR TITLE
Initial version of the mms restore image.

### PR DESCRIPTION
**Pull request by danharvey**
- Request a restore
- Wait and then download
- Convert and import into standalone mongo instance

### CODE REVIEW

**Comment by vaijab** [comment]
Please add `LICENSE` file.

**Comment by marcinc** [comment]
+1 for license. LG otherwise.

**Comment by danharvey** [comment]
Added License and sample config.

**Comment by marcinc** [comment]
Cool. LG.

**Comment by vaijab** [comment]
LGTM

**Pull request merged**
